### PR TITLE
Made BlockDrops Async

### PR DESCRIPTION
**Pull request by MakerTim**
ExecutorService creates and manages the threads
then saving it in a list what is all going on
for each block, submit a task to get all drops
and then sync all blocks back to the main thread

Should be as fast as the slowest block; or at leased MUCH faster then before

### CODE REVIEW

**Comment by MakerTim** [comment]
Since Gitlab can't make a good change preview
image

**Comment by KidsDontPlay** [comment]
I will check out this next week

**Comment by MakerTim** [comment]
np, just a friendly reminder :)
creating a modpack with installing this from the start will help a lot for the playtesters of my pack
and as general faster loading speeds are awesome

**Comment by KidsDontPlay** [comment]
does the code create a thread for every block?
could the cpu handle ~4000 threads?

**Comment by KidsDontPlay** [comment]
Ok. I tested it with All the mods 3 which has 6000 blockstates and it worked fine.
With multithreading: 338 seconds
Without multithreading: 1000 seconds

**Comment by MakerTim** [comment]
since java uses virtual threads and not hardware threads, it is save to create many threads
a bit of a overhead; but seemed a lot faster in usage

**Comment by KidsDontPlay** [comment]
I changed it a little bit. https://hastebin.com/iqalopigup.coffeescript
what do you think?
And I had another idea. I start a thread that calculates block drops in PreInit and wait for it in PostInit.
like this https://hastebin.com/ihuvekidoc.cs

**Comment by MakerTim** [comment]
are all blocks registerd in pre-init? dont know??
if so, sounds like a plan!

It looks promising

**Pull request merged**
